name: chatapp
description: A new Flutter project.
publish_to: 'none'
version: 0.2.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_secure_storage: ^8.0.0
  http: ^1.1.0
  socket_io_client: ^2.0.3+1
  intl: ^0.18.0
  chat_bubbles: ^1.5.0
  sembast: ^3.5.0
  path_provider: ^2.1.1
  path: ^1.8.2
  # provider: ^6.1.1
  # flutter_local_notifications: ^15.1.1
  # flutter_timezone: ^1.0.4
  # http: ^0.13.4
  # image: ^3.0.8
  # device_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
